In [1]:
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import datetime
import plotly.express as px
import math
import warnings
warnings.filterwarnings('ignore')
import time
from time import perf_counter
import glob
import sys
sys.path.append('C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/notebook/tweet_utils')
import tweets_utils
import csv
import importlib
import seaborn as sns
path = glob.glob("C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/")
%autosave 3600

Autosaving every 3600 seconds

## Indice
- [Check if the users are inside current data](#check)
- [Collecting data and create DataFrame](#collecting_350)
- [Merge data collected inside and outside DataFrame](#merge)
- [Investigation](#investigation)

In [2]:
# x = pd.DataFrame(x, columns=["screen_name"])
# x.to_csv("C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/csv/all_good_users.csv", 
#          line_terminator="\n", index=False, encoding="utf-8")

In [3]:
df = pd.read_csv(path[0] + "/csv/all_good_users.csv", low_memory=False, lineterminator="\n")
df

        screen_name
0      JeremyFarrar
1    AdamJKucharski
2          cmyeaton
3    MarionKoopmans
4      nataliexdean
..              ...
255     MattFrieman
256  Iplaywithgerms
257    greg_folkers
258      jmayer0716
259     robyn_s_lee

[260 rows x 1 columns]

# Check if 350 good users are inside current data
<a id="check"/>

In [3]:
files_tweets = glob.glob("F:/Supsi/COVID-19-Tweets/*/tweets.csv")
user_screen_name = []
cols_tweets = [u'user_screen_name']

In [17]:
result = []
importlib.reload(tweets_utils)
start_time = time.perf_counter()
j = 0
for filename in files_tweets:
    print(f"Reading file: {filename}")
    result.extend(tweets_utils.process_all_data(filename, cols_tweets, True, list(df["screen_name"])))
    lista = result[j]
    j = j + 1
    print(f"Mese numero {j}")
    for i in range(len(lista)):

        user_screen_name.extend(lista[i]["df"])
stop_time = time.perf_counter()
print("Time: ",stop_time-start_time)

In [34]:
lst_found = list(set(user_screen_name))
val_350 = len(df["screen_name"])
val_found = len(user_screen_name)
print(f"{round(val_found/val_350,2)}%")
print(f"presenti in {len(lst_found)}")

93.66%
presenti in 338

In [4]:
diff = list(set(df["screen_name"]) - set(lst_found))
diff

# Collecting data
<a id="collecting_350" />

In [4]:
for i in pd.read_csv("F:/Supsi/COVID-19-Tweets/2020-01/tweets.csv", chunksize=10, lineterminator="\n", low_memory=False):
    break
i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 46 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         10 non-null     int64
 1   id_str                     10 non-null     int64
 2   created_at                 10 non-null     object
 3   user_id                    10 non-null     int64
 4   user_screen_name           10 non-null     object
 5   user_verified              10 non-null     bool
 6   user_created_at            10 non-null     object
 7   text                       10 non-null     object
 8   source                     10 non-null     object
 9   coordinates                0 non-null      float64
 10  is_quote_status            10 non-null     bool
 11  retweet_count              10 non-null     int64
 12  favorite_count             10 non-null     int64
 13  favorited                  10 non-null     bool
 14  retweeted                  10 non-null     bool
 15  lang                       10 non-null     object
 16  in_reply_to_status_id      0 non-null      float64
 17  in_reply_to_status_id_str  0 non-null      float64
 18  in_reply_to_user_id        0 non-null      float64
 19  in_reply_to_user_id_str    0 non-null      float64
 20  in_reply_to_screen_name    0 non-null      float64
 21  rt_coordinates             0 non-null      float64
 22  rt_created_at              9 non-null      object
 23  rt_in_reply_to_status_id   1 non-null      float64
 24  rt_in_reply_to_user_id     2 non-null      float64
 25  rt_lang                    9 non-null      object
 26  rt_favourite_count         9 non-null      float64
 27  rt_id                      9 non-null      float64
 28  rt_user_id                 9 non-null      float64
 29  rt_user_screen_name        9 non-null      object
 30  rt_user_created_at         9 non-null      object
 31  rt_user_verified           9 non-null      object
 32  rt_user_followers_count    9 non-null      float64
 33  rt_user_friends_count      9 non-null      float64
 34  rt_user_favourites_count   9 non-null      float64
 35  quoted_status_id           1 non-null      float64
 36  quoted_status_text         0 non-null      float64
 37  quoted_status_created_at   0 non-null      float64
 38  quoted_user_id             0 non-null      float64
 39  quoted_user_created_at     0 non-null      float64
 40  hashtags                   10 non-null     object
 41  symbols                    10 non-null     object
 42  user_mentions              10 non-null     object
 43  urls                       10 non-null     object
 44  polls                      10 non-null     object
 45  media                      10 non-null     object
dtypes: bool(4), float64(20), int64(5), object(17)
memory usage: 3.4+ KB

In [5]:
cols = ["id", "id_str", "user_id", "user_screen_name", "text","in_reply_to_status_id",
        "in_reply_to_status_id_str" ,"in_reply_to_user_id" ,"in_reply_to_user_id_str" ,"in_reply_to_screen_name",
        "rt_created_at", "rt_in_reply_to_status_id", "rt_in_reply_to_user_id", "rt_id", "rt_user_id", "rt_created_at",
        "rt_user_screen_name", "quoted_status_id" ,"quoted_status_text" ,"quoted_status_created_at", "quoted_user_id",
        "quoted_user_created_at", "hashtags", "user_mentions", "urls", "created_at", "retweet_count"]

In [6]:
files_tweets = glob.glob("F:/Supsi/COVID-19-Tweets/*/tweets.csv")
result = []
data = pd.DataFrame()
importlib.reload(tweets_utils)
start_time = time.perf_counter()
j = 0
for filename in files_tweets:
    print(f"Reading file: {filename}")
    result.extend(tweets_utils.process_all_data(filename, cols, True, df["screen_name"]))
    lista = result[j]
    j = j + 1
    print(f"Mese numero {j}")
    for i in range(len(lista)):
        data = data.append(lista[i]["df"])
    print(len(data))
stop_time = time.perf_counter()
print("Time: ",stop_time-start_time)

Reading file: F:/Supsi/COVID-19-Tweets\2020-01\tweets.csv
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Mese numero 1
28933
Reading file: F:/Supsi/COVID-19-Tweets\2020-02\tweets.csv
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Mese numero 2
103832
Reading file: F:/Supsi/COVID-19-Tweets\2020-03\tweets.csv
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Processing chunk 14
Processing chunk 15
Mese numero 3
219373
Reading file: F:/Supsi/COVID-19-Tweets\2020-04\tweets.csv
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Mese numero 4
277356
Reading file: F:/Supsi/COVID-19-Tweets\2020-05\tweets.csv
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Processing chunk 14
Processing chunk 15
Processing chunk 16
Processing chunk 17
Processing chunk 18
Processing chunk 19
Processing chunk 20
Processing chunk 21
Processing chunk 22
Processing chunk 23
Processing chunk 24
Mese numero 5
433964
Time:  2937.0155374

In [7]:
data = data.reset_index(drop = True)
data

,id,id_str,created_at,user_id,user_screen_name,text,retweet_count,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,rt_user_id,rt_user_screen_name,quoted_status_id,quoted_status_text,quoted_status_created_at,quoted_user_id,quoted_user_created_at,hashtags,user_mentions,urls
0,1219801689336664064,1.219802e+18,Wed Jan 22 01:59:20 +0000 2020,9.213730e+17,FonsecaVintage,@Laurie_Garrett @MackayIM The public is unders...,0.0,1.219767e+18,1.219767e+18,2.992740e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhanvirus', 'indices': [66, 77]}, ...","[{'screen_name': 'Laurie_Garrett', 'name': 'La...",[]
1,1219811978404945925,1.219812e+18,Wed Jan 22 02:40:13 +0000 2020,2.963912e+08,MicroWavesSci,CDC details first U.S. case of novel virus spr...,9.0,NaN,NaN,NaN,...,4.443826e+07,matthewherper,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'matthewherper', 'name': 'Mat...","[{'url': 'https://t.co/IgeMsQXW4V', 'expanded_..."
2,1219810588873961473,1.219811e+18,Wed Jan 22 02:34:42 +0000 2020,1.071979e+18,KindrachukJason,.@NYTimes is reporting the first U.S. case of ...,20.0,NaN,NaN,NaN,...,7.641714e+07,IDSAInfo,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhan', 'indices': [64, 70]}, {'tex...","[{'screen_name': 'IDSAInfo', 'name': 'IDSA', '...","[{'url': 'https://t.co/Cm8rjaZHpi', 'expanded_..."
3,1219812237633904641,1.219812e+18,Wed Jan 22 02:41:15 +0000 2020,2.750369e+09,vtaylor9188,"From homeland perspective @DHSgov, the CDC was...",7.0,NaN,NaN,NaN,...,2.146136e+07,juliettekayyem,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'juliettekayyem', 'name': 'Ju...",[]
4,1219807084830773248,1.219807e+18,Wed Jan 22 02:20:46 +0000 2020,2.875332e+09,winder_gill,"@BogochIsaac It's scary, but I'm sure there wi...",0.0,1.219708e+18,1.219708e+18,1.093695e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'BogochIsaac', 'name': 'Isaac...","[{'url': 'https://t.co/PVcS6aLBbx', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433959,1262355670189305859,1.262356e+18,Mon May 18 12:13:39 +0000 2020,2.624889e+09,Joffa1970Joffa,👏 the 3 best 🇳🇿🇹🇼🇮🇸\nand their leadership vs ...,568.0,NaN,NaN,NaN,...,8.662684e+07,EricTopol,NaN,NaN,NaN,NaN,NaN,"[{'text': 'COVID19', 'indices': [60, 68]}]","[{'screen_name': 'EricTopol', 'name': 'Eric To...",[]
433960,1263349623998967808,1.263350e+18,Thu May 21 06:03:16 +0000 2020,5.773070e+07,thack86,We launched through a letter to every governor...,316.0,NaN,NaN,NaN,...,1.383272e+09,ASlavitt,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ASlavitt', 'name': 'Andy Sla...",[]
433961,1264561651673677824,1.264562e+18,Sun May 24 14:19:26 +0000 2020,7.410451e+17,Origamilady42,A TRUE PANDEMIC MYSTERY SOLVED.\nIt has been a...,1553.0,NaN,NaN,NaN,...,2.146136e+07,juliettekayyem,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'juliettekayyem', 'name': 'Ju...",[]
433962,1260025927406243840,1.260026e+18,Tue May 12 01:56:05 +0000 2020,2.416479e+09,redtaz1951,We literally left them a 69-page Pandemic Play...,63910.0,NaN,NaN,NaN,...,2.488840e+08,RonaldKlain,1.259999e+18,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'RonaldKlain', 'name': 'Ronal...",[]
433963,1266226534051975168,1.266227e+18,Fri May 29 04:35:05 +0000 2020,8.103540e+07,twodogsing,COVID Update May 28: If Trump has done one sim...,2404.0,NaN,NaN,NaN,...,1.383272e+09,ASlavitt,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ASlavitt', 'name': 'Andy Sla...",[]

In [8]:
# data = data.reset_index(drop = True)
path = glob.glob("F:/Supsi/COVID-19-Tweets/large_files/ccdh/")
path_w = glob.glob("C:/Users/gianl/Downloads/")
data.to_csv(path_w[0] + "all_good_tweets_inside.csv", index = False, line_terminator = "\n", encoding = "utf-8")

# Merge DF and write
<a id="merge"/>

In [9]:
df = pd.read_csv(path[0] + "all_good_tweets_inside.csv", low_memory=False, lineterminator = "\n")
df

,id,id_str,created_at,user_id,user_screen_name,text,retweet_count,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,rt_user_id,rt_user_screen_name,quoted_status_id,quoted_status_text,quoted_status_created_at,quoted_user_id,quoted_user_created_at,hashtags,user_mentions,urls
0,1219801689336664064,1.219802e+18,Wed Jan 22 01:59:20 +0000 2020,9.213730e+17,FonsecaVintage,@Laurie_Garrett @MackayIM The public is unders...,0.0,1.219767e+18,1.219767e+18,2.992740e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhanvirus', 'indices': [66, 77]}, ...","[{'screen_name': 'Laurie_Garrett', 'name': 'La...",[]
1,1219811978404945925,1.219812e+18,Wed Jan 22 02:40:13 +0000 2020,2.963912e+08,MicroWavesSci,CDC details first U.S. case of novel virus spr...,9.0,NaN,NaN,NaN,...,4.443826e+07,matthewherper,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'matthewherper', 'name': 'Mat...","[{'url': 'https://t.co/IgeMsQXW4V', 'expanded_..."
2,1219810588873961473,1.219811e+18,Wed Jan 22 02:34:42 +0000 2020,1.071979e+18,KindrachukJason,.@NYTimes is reporting the first U.S. case of ...,20.0,NaN,NaN,NaN,...,7.641714e+07,IDSAInfo,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhan', 'indices': [64, 70]}, {'tex...","[{'screen_name': 'IDSAInfo', 'name': 'IDSA', '...","[{'url': 'https://t.co/Cm8rjaZHpi', 'expanded_..."
3,1219812237633904641,1.219812e+18,Wed Jan 22 02:41:15 +0000 2020,2.750369e+09,vtaylor9188,"From homeland perspective @DHSgov, the CDC was...",7.0,NaN,NaN,NaN,...,2.146136e+07,juliettekayyem,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'juliettekayyem', 'name': 'Ju...",[]
4,1219807084830773248,1.219807e+18,Wed Jan 22 02:20:46 +0000 2020,2.875332e+09,winder_gill,"@BogochIsaac It's scary, but I'm sure there wi...",0.0,1.219708e+18,1.219708e+18,1.093695e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'BogochIsaac', 'name': 'Isaac...","[{'url': 'https://t.co/PVcS6aLBbx', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433959,1262355670189305859,1.262356e+18,Mon May 18 12:13:39 +0000 2020,2.624889e+09,Joffa1970Joffa,👏 the 3 best 🇳🇿🇹🇼🇮🇸\nand their leadership vs ...,568.0,NaN,NaN,NaN,...,8.662684e+07,EricTopol,NaN,NaN,NaN,NaN,NaN,"[{'text': 'COVID19', 'indices': [60, 68]}]","[{'screen_name': 'EricTopol', 'name': 'Eric To...",[]
433960,1263349623998967808,1.263350e+18,Thu May 21 06:03:16 +0000 2020,5.773070e+07,thack86,We launched through a letter to every governor...,316.0,NaN,NaN,NaN,...,1.383272e+09,ASlavitt,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ASlavitt', 'name': 'Andy Sla...",[]
433961,1264561651673677824,1.264562e+18,Sun May 24 14:19:26 +0000 2020,7.410451e+17,Origamilady42,A TRUE PANDEMIC MYSTERY SOLVED.\nIt has been a...,1553.0,NaN,NaN,NaN,...,2.146136e+07,juliettekayyem,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'juliettekayyem', 'name': 'Ju...",[]
433962,1260025927406243840,1.260026e+18,Tue May 12 01:56:05 +0000 2020,2.416479e+09,redtaz1951,We literally left them a 69-page Pandemic Play...,63910.0,NaN,NaN,NaN,...,2.488840e+08,RonaldKlain,1.259999e+18,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'RonaldKlain', 'name': 'Ronal...",[]
433963,1266226534051975168,1.266227e+18,Fri May 29 04:35:05 +0000 2020,8.103540e+07,twodogsing,COVID Update May 28: If Trump has done one sim...,2404.0,NaN,NaN,NaN,...,1.383272e+09,ASlavitt,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ASlavitt', 'name': 'Andy Sla...",[]

In [10]:
df_2 = pd.read_csv(path[0] + "all_good_tweets.csv", low_memory=False, lineterminator = "\n", usecols=cols)
df_2

,id,id_str,created_at,user_id,user_screen_name,text,retweet_count,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,rt_user_id,rt_user_screen_name,quoted_status_id,quoted_status_text,quoted_status_created_at,quoted_user_id,quoted_user_created_at,hashtags,user_mentions,urls
0,1451094027605000194,1451094027605000194,2021-10-21 07:52:30+00:00,1489776218,JeremyFarrar,@Alheri @JeremyFarrar https://t.co/NDtc9GYh6B,9,NaN,NaN,NaN,...,1.352962e+09,MackayIM,1.434034e+18,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'MackayIM', 'name': 'ɪᴀɴ ᴍ. ᴍ...","[{'url': 'https://t.co/NDtc9GYh6B', 'expanded_..."
1,1450947380212293638,1450947380212293638,2021-10-20 22:09:47+00:00,1489776218,JeremyFarrar,@pmb1000 Sad thing is it hasn’t changed since ...,0,1.450946e+18,1.450946e+18,3.209044e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'pmb1000', 'name': 'Philip Ba...",[]
2,1450946370425266179,1450946370425266179,2021-10-20 22:05:46+00:00,1489776218,JeremyFarrar,"Acknowledging original idea Reason, James (199...",2,1.450937e+18,1.450937e+18,1.489776e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],"[{'url': 'https://t.co/o5m3dtQxQU', 'expanded_..."
3,1450945229738151936,1450945229738151936,2021-10-20 22:01:14+00:00,1489776218,JeremyFarrar,@JoePajak And have missed your graphs and grap...,0,1.450942e+18,1.450942e+18,9.014616e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'JoePajak', 'name': 'Dr Joe P...",[]
4,1450945151090798595,1450945151090798595,2021-10-20 22:00:55+00:00,1489776218,JeremyFarrar,@JoePajak Vaccines/drugs mean Oct21 not a repe...,6,1.450942e+18,1.450942e+18,9.014616e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'JoePajak', 'name': 'Dr Joe P...","[{'url': 'https://t.co/LmbP2QehMR', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733622,309010148788146176,309010148788146176,2013-03-05 18:38:55+00:00,794631618,richardneher,Deleterious synonymous mutations hitchhike to ...,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/MdoNtkSKXt', 'expanded_u..."
733623,299306696747151361,299306696747151361,2013-02-07 00:00:52+00:00,794631618,richardneher,"Genetic draft, selective interference, and pop...",2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/USCB4Mcf', 'expanded_url..."
733624,245210618817310722,245210618817310722,2012-09-10 17:22:21+00:00,794631618,richardneher,Michael Eisen: The lesson I learned from ENCOD...,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ShareThis', 'name': 'ShareTh...","[{'url': 'http://t.co/fOuF6I1S', 'expanded_url..."
733625,243386067858894849,243386067858894849,2012-09-05 16:32:15+00:00,794631618,richardneher,Our paper: Genealogies of rapidly adapting pop...,3,NaN,NaN,NaN,...,7.685627e+08,Haldanessieve,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/GddxNGW4', 'expanded_url..."
733626,243060604343046144,243060604343046144,2012-09-04 18:58:58+00:00,794631618,richardneher,Genealogies of rapidly adapting populations ht...,1,NaN,NaN,NaN,...,7.685627e+08,Haldanessieve,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/L9s1a8SU', 'expanded_url..."

In [11]:
df_merged = data.append(df_2)
df_merged = df_merged.drop_duplicates(subset=['id'])
df_merged = df_merged.reset_index(drop=True)

In [12]:
df_merged

,id,id_str,created_at,user_id,user_screen_name,text,retweet_count,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,rt_user_id,rt_user_screen_name,quoted_status_id,quoted_status_text,quoted_status_created_at,quoted_user_id,quoted_user_created_at,hashtags,user_mentions,urls
0,1219801689336664064,1.219802e+18,Wed Jan 22 01:59:20 +0000 2020,9.213730e+17,FonsecaVintage,@Laurie_Garrett @MackayIM The public is unders...,0.0,1.219767e+18,1.219767e+18,2.992740e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhanvirus', 'indices': [66, 77]}, ...","[{'screen_name': 'Laurie_Garrett', 'name': 'La...",[]
1,1219811978404945925,1.219812e+18,Wed Jan 22 02:40:13 +0000 2020,2.963912e+08,MicroWavesSci,CDC details first U.S. case of novel virus spr...,9.0,NaN,NaN,NaN,...,44438256.0,matthewherper,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'matthewherper', 'name': 'Mat...","[{'url': 'https://t.co/IgeMsQXW4V', 'expanded_..."
2,1219810588873961473,1.219811e+18,Wed Jan 22 02:34:42 +0000 2020,1.071979e+18,KindrachukJason,.@NYTimes is reporting the first U.S. case of ...,20.0,NaN,NaN,NaN,...,76417139.0,IDSAInfo,NaN,NaN,NaN,NaN,NaN,"[{'text': 'Wuhan', 'indices': [64, 70]}, {'tex...","[{'screen_name': 'IDSAInfo', 'name': 'IDSA', '...","[{'url': 'https://t.co/Cm8rjaZHpi', 'expanded_..."
3,1219812237633904641,1.219812e+18,Wed Jan 22 02:41:15 +0000 2020,2.750369e+09,vtaylor9188,"From homeland perspective @DHSgov, the CDC was...",7.0,NaN,NaN,NaN,...,21461359.0,juliettekayyem,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'juliettekayyem', 'name': 'Ju...",[]
4,1219807084830773248,1.219807e+18,Wed Jan 22 02:20:46 +0000 2020,2.875332e+09,winder_gill,"@BogochIsaac It's scary, but I'm sure there wi...",0.0,1.219708e+18,1.219708e+18,1.093695e+18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'BogochIsaac', 'name': 'Isaac...","[{'url': 'https://t.co/PVcS6aLBbx', 'expanded_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163841,309010148788146176,3.090101e+17,2013-03-05 18:38:55+00:00,7.946316e+08,richardneher,Deleterious synonymous mutations hitchhike to ...,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/MdoNtkSKXt', 'expanded_u..."
1163842,299306696747151361,2.993067e+17,2013-02-07 00:00:52+00:00,7.946316e+08,richardneher,"Genetic draft, selective interference, and pop...",2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/USCB4Mcf', 'expanded_url..."
1163843,245210618817310722,2.452106e+17,2012-09-10 17:22:21+00:00,7.946316e+08,richardneher,Michael Eisen: The lesson I learned from ENCOD...,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'ShareThis', 'name': 'ShareTh...","[{'url': 'http://t.co/fOuF6I1S', 'expanded_url..."
1163844,243386067858894849,2.433861e+17,2012-09-05 16:32:15+00:00,7.946316e+08,richardneher,Our paper: Genealogies of rapidly adapting pop...,3.0,NaN,NaN,NaN,...,768562657.0,Haldanessieve,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/GddxNGW4', 'expanded_url..."
1163845,243060604343046144,2.430606e+17,2012-09-04 18:58:58+00:00,7.946316e+08,richardneher,Genealogies of rapidly adapting populations ht...,1.0,NaN,NaN,NaN,...,768562657.0,Haldanessieve,NaN,NaN,NaN,NaN,NaN,[],"[{'screen_name': 'Haldanessieve', 'name': 'Hal...","[{'url': 'http://t.co/L9s1a8SU', 'expanded_url..."

In [13]:
# path = glob.glob("C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/")
df_merged.to_csv(path_w[0] + "all_good.csv", line_terminator="\n", encoding="utf-8", index=False)

### Investigation
<a id="investigation"/>

In [70]:
path = glob.glob("C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/large_files/ccdh/")
df = pd.read_csv(path[0] + "all_good_tweet_merge.csv", low_memory=False, lineterminator="\n")
df

,id,created_at,user_id,user_screen_name,text,retweet_count,in_reply_to_user_id,in_reply_to_screen_name,rt_user_id,rt_user_screen_name,quoted_status_text,quoted_status_created_at,quoted_user_id,hashtags,urls
0,1219810588873961473,Wed Jan 22 02:34:42 +0000 2020,1.071979e+18,KindrachukJason,.@NYTimes is reporting the first U.S. case of ...,20.0,NaN,NaN,7.641714e+07,IDSAInfo,NaN,NaN,NaN,"[{'text': 'Wuhan', 'indices': [64, 70]}, {'tex...","[{'url': 'https://t.co/Cm8rjaZHpi', 'expanded_..."
1,1219950693244710913,Wed Jan 22 11:51:25 +0000 2020,2.527945e+08,picardonhealth,People have recently asked me where I get news...,15.0,NaN,NaN,3.343015e+08,shoffmania,NaN,NaN,NaN,"[{'text': '2019nCoV', 'indices': [81, 90]}]",[]
2,1219950687083204608,Wed Jan 22 11:51:24 +0000 2020,3.061632e+09,EvolveDotZoo,nCoV's relationship to bat coronaviruses &amp;...,16.0,NaN,NaN,7.076683e+17,virological_org,NaN,NaN,NaN,[],"[{'url': 'https://t.co/1x996JChtk', 'expanded_..."
3,1219945721778012161,Wed Jan 22 11:31:40 +0000 2020,2.715047e+09,EckerleIsabella,"Right now, WHO is convening IHR Emergency Comm...",4.0,NaN,NaN,3.258333e+08,nikkishindo,NaN,NaN,NaN,[],[]
4,1219958577902866438,Wed Jan 22 12:22:45 +0000 2020,1.133733e+18,MattFrieman,We are sharing our initial analysis of the new...,230.0,NaN,NaN,5.562599e+08,john_jxw,NaN,NaN,NaN,"[{'text': 'Wuhan', 'indices': [61, 67]}, {'tex...",[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750815,309010148788146176,2013-03-05 18:38:55+00:00,7.946316e+08,richardneher,Deleterious synonymous mutations hitchhike to ...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'url': 'http://t.co/MdoNtkSKXt', 'expanded_u..."
750816,299306696747151361,2013-02-07 00:00:52+00:00,7.946316e+08,richardneher,"Genetic draft, selective interference, and pop...",2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'url': 'http://t.co/USCB4Mcf', 'expanded_url..."
750817,245210618817310722,2012-09-10 17:22:21+00:00,7.946316e+08,richardneher,Michael Eisen: The lesson I learned from ENCOD...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],"[{'url': 'http://t.co/fOuF6I1S', 'expanded_url..."
750818,243386067858894849,2012-09-05 16:32:15+00:00,7.946316e+08,richardneher,Our paper: Genealogies of rapidly adapting pop...,3.0,NaN,NaN,7.685627e+08,Haldanessieve,NaN,NaN,NaN,[],"[{'url': 'http://t.co/GddxNGW4', 'expanded_url..."
750819,243060604343046144,2012-09-04 18:58:58+00:00,7.946316e+08,richardneher,Genealogies of rapidly adapting populations ht...,1.0,NaN,NaN,7.685627e+08,Haldanessieve,NaN,NaN,NaN,[],"[{'url': 'http://t.co/L9s1a8SU', 'expanded_url..."

In [71]:
replies = df[df["in_reply_to_user_id"].notna()]
retweet = df[df["rt_user_id"].notna()]
quotes = df[df["quoted_status_created_at"].notna() & df["in_reply_to_user_id"].isna() & df["rt_user_id"].isna()]
original = df[df["quoted_status_created_at"].isna() & df["in_reply_to_user_id"].isna() & df["rt_user_id"].isna()]