In [1]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')
import time
from time import perf_counter
import glob
import csv
import importlib
import seaborn as sns
import json
from tqdm.notebook import tqdm
import sys
sys.path.append('C:/Users/gianl/Desktop/Gi/Supsi/BachelorProject/notebook/tweet_utils')
import tweets_utils

In [5]:
path = 'F:/COVID-19-Light/parquet/2020-08-Tweets/2020-08-2.parquet'
df = pd.read_parquet(path, engine="fastparquet")
df

,in_reply_to_user_id,in_reply_to_screen_name,rt_created_at,quoted_status_id,hashtags,urls
0,NaN,None,Wed Aug 19 22:06:29 +0000 2020,NaN,[],[]
1,NaN,None,Thu Aug 20 05:40:10 +0000 2020,NaN,[],[]
2,807095.0,nytimes,None,NaN,[],[]
3,NaN,None,Mon Aug 17 18:23:37 +0000 2020,NaN,[],[]
4,NaN,None,Wed Aug 19 12:18:06 +0000 2020,NaN,[],[]
...,...,...,...,...,...,...
14999995,NaN,None,Wed Aug 26 13:00:31 +0000 2020,NaN,"[{'text': 'StayHome', 'indices': [60, 69]}]",[]
14999996,NaN,None,Fri Aug 07 09:54:25 +0000 2020,NaN,"[{'text': 'COVID19', 'indices': [110, 118]}, {...","[{'url': 'https://t.co/aHKjDHvZoH', 'expanded_..."
14999997,NaN,None,None,1.298592e+18,[],"[{'url': 'https://t.co/0NcuwcsqLK', 'expanded_..."
14999998,NaN,None,Wed Aug 26 10:11:00 +0000 2020,NaN,[],[]
14999999,NaN,None,None,NaN,[],[]